["forbid"]                              #设置目标站点不进行种子转发的内容
"word" = ["","",""]                     #设置主标题中包含的关键字，可以多个，置空为不限制。
"type" = ["","",""]                     #设置类型中不转的关键字，可以多个，置空为不限制。可选范围：【电影，电视剧，综艺，音乐，体育，动漫，纪录片】
"standard" = ["","",""]                 #设置分辨率中不转的关键字，可以多个，置空为不限制。可选范围：【480p，480i，720p，720i，1080p，1080i，2160p，4380p】
"tag" = ["","",""]                      #设置一些特殊不转的关键字，可以多个，置空为不限制。可选范围：【分集】