"model_site" = ["site1", "site2", "site3"]
"www.hddolby.com" = ["hdvideo.one"]
"hdvideo.one" = ["www.hddolby.com"]
"www.agsvpt.com" =  [""]
"ptvicomo.net" = [""]
"ubits.club" = [""]
"www.hdkyl.in" = [""]
"carpt.net" = [""]
"ptlgs.org" = [""]
"zmpt.cc" = [""]
"raingfh.top" = [""]
"leaves.red" = [""]
"lemonhd.club" = [""]
"njtupt.top" = [""]
"pt.btschool.club" = [""]
"www.qingwapt.com" = [""]
"hdfans.org" = [""]
"hdarea.club" = [""]
"pterclub.net" = [""]
"kufei.org" = [""]
"pt.hdclone.org" = [""]
"rousi.zip" = [""]
"www.icc2022.com" = [""]
"1ptba.com" = [""]
"ptsbao.club" = [""]
"www.devtracker.me" = [""]
"cyanbug.net" = [""]
"pandapt.net" = [""]
"totheglory.im" = [""]
"www.ptzone.xyz" = [""]
"pt.soulvoice.club" = [""]
"pt.0ff.cc" = [""]
"hdatmos.club" = [""]
"hdhome.org" = [""]
"hdtime.org" = [""]
"pt.upxin.net" = [""]
"www.joyhd.net" = [""]
"www.okpt.net" = [""]
"www.oshen.win" = [""]
"ptchina.org" = [""]
"pthome.net" = [""]
"ptcafe.club" = [""]
"crabpt.vip" = [""]
"www.dragonhd.xyz" = [""]
"hspt.club" = [""]
"hdbao.cc" = [""]
"www.ptlover.cc" = [""]
"ptfans.cc" = [""]
"pt.gtkpw.xyz" = [""]
"hdpt.xyz" = [""]
"www.hitpt.com" = [""]
"sanpro.pw" = [""]
"torrenthub.club" = [""]
"pt.xingyungept.org" = [""]
"cspt.top" = [""]
"tmpt.top" = [""]
"hudbt.hust.edu.cn" = [""]
"nanyangpt.com" = [""]
"tjupt.org" = [""]
"wintersakura.net" = [""]
"et8.org" = [""]
"pt.eastgame.org" = [""]
"hdcity.city" = [""]
"52pt.site" = [""]
"audiences.me" = [""]
"pt.ying.us.kg" = [""]
"sewerpt.com" = [""]
"lemonhd.net" = [""]
"bilibili.download" = [""]
"pt.novahd.top" = [""]
"duckboobee.org" = [""]
"pt.luckpt.de" = [""]
"pt.lajidui.top" = [""]
"13city.org" = [""]
"zrpt.cc" = [""]
"www.yhpp.cc" = [""]
"pt.muxuege.org" = [""]
"cc.mypt.cc" = [""]
"nex.jivon.de" = [""]
"sbpt.link" = [""]
"pt.aling.de" = [""]
"cangbao.ge" = [""]
"dubhe.site" = [""]
"ptlao.top" = [""]
"longpt.org" = [""]