port = 45678                                        #工具使用的通信端口
pt_gen = ""                                         #填自建的，不带豆瓣Cookies的PTGEN地址
pt_gen_ck = ""                                      #填自建的，带豆瓣Cookies的PTGEN地址
tool_api = "127.0.0.1"                              #工具自身使用的通信IP，与QB相同主机时默认即可，与QB不同主机时填写具体的【http(s)://ip:port】port后不加/
who_am_i = "DTU"                                    #通知时明确是哪台分布式应用
authorize_code = "1C80009CC32A9A921675770B3EE19ABC" #鉴权识别码，该码会动态增加已支持的站点
annotations = ""                                    #填写期望在副标题最后添加的说明内容，可自行修改
douban_ck = ""                                      #非必填，当无法查询出豆瓣编号时，可以尝试增加自己的豆瓣CK查询
is_debug = false                                    #debug日志开关，修改后需要重启容器【默认关闭】
rss_start_time = 1                                  #从每小时的第N分钟起执行自动拉取RSS总控任务【单位是分钟：0-59】，建议每个DTU值不相同
rss_task_interval = 10                              #每间隔N分钟执行自动拉取RSS总控任务【单位是分钟：0-59】
time_to_upload = 5                                  #每N分钟执行一次扫描发种【单位是分钟：0-59】
time_to_delete = true                               #是否开启自动删除N小时前种子的功能【默认开启】，目的释放硬盘空间，以种子下完DTU收到通知的时间为算
time_to_delete_interval = 24                        #默认删除间隔为24小时，请自行输入整小时数，以种子下完DTU收到通知的时间为算
time_to_delete_time = 30                            #从0点开始每N分钟执行一次自动删种任务【单位是分钟：0-59】，以种子下完DTU收到通知的时间为算
time_to_stop = true                                 #是否开启自动限速做种数N人以上种子的功能【默认开启】，目的释放上行带宽
time_to_stop_uper = 4                               #自动限速做种数人数大于配置值的
time_to_stop_time = 30                              #从0点开始每N分钟执行一次自动限速【单位是分钟：0-59】
time_to_stop_torrent = true                         #限速后同时暂停做种，目的释放上行带宽
time_to_stop_delete = false                         #是否开启检测源种和发布种均大于自动停止做种数，大于立刻删除种子，目的释放硬盘空间
move_source_time = 10                               #从0点开始每N分钟执行一次限速后转移【单位是分钟：0-59】
move_source_speed = 50                              #判断上传速度小于N后进行转移【单位是KB】
move_source_flag = false                            #是否开启限速后移动到新路径功能【默认关闭】，目的从SSD移动到HDD存储。
move_source_path = "/downloads/"                    #期望移动到的新路径，此路径必须是QB可读取的路径
http_porxy = "http://ip:port"                       #代理，用于访问无法连接的RSS
rss_control_host = "http://127.0.0.1:56789"         #RSS总控的调用地址
rss_pause = false                                   #暂停拉取新种子
concurrency_upload_speed = 100                      #允许同时做种上传的种子上传速度阈值，低于此值不进行计算，单位KB
concurrency_upload_num = 5                          #允许同时做种上传的种子最大数量，大于该值时不进行源种下载。
concurrency_upload_magnify = 3                      #允许同时做种上传的种子最大数量的倍数，大于数量乘倍数之后的值时不进行资源发布。
min_wait_upload = 3                                 #大于未发布种子数N的时候，不进行RSS拉取

[qb_server]                                         #QB相关设置，强烈建议QB使用4.6.0版本，过高版本接口调不通
url = "http://127.0.0.1"                            #QB的webui地址，docker部署方式可直接默认
port = 8080                                         #QB的webui端口，docker部署方式可直接默认
user = "admin"                                      #QB的webui用户名
password = ""                                       #QB的webui密码
verify = false                                      #QB本地部署默认false
down_queue = 3                                      #建议和QB设置的同时下载数一致
download_path = "/downloads/"                       #QB中的点设置-下载标签中的默认下载地址栏的内容，也可以自己写QB可读取的任意地址
tags = "ARDTU"                                      #QB中的标签名称
skip_checking = false                               #QB中是否跳过校验
super_seeding = true                                #QB中是否开启超级做种
up_speed_limit = 50                                 #对所有种子进行上传速度限制，单位MB，定义与QB中的MB一样。
down_speed_limit = 50                               #对源站下载种子进行下载速度限制，单位MB，定义与QB中的MB一样。
up_queue_max = 50
up_queue_min = 4
control_speed = false

[domain]                                            #当网站有备用域名时，自行修改域名映射
"www.agsvpt.com" = "www.agsvpt.com"
"ptvicomo.net" = "ptvicomo.net"
"ubits.club" = "ubits.club"
"www.hdkyl.in" = "www.hdkyl.in"
"carpt.net" = "carpt.net"
"ptlgs.org" = "ptlgs.org"
"zmpt.cc" = "zmpt.cc"
"raingfh.top" = "raingfh.top"
"leaves.red" = "leaves.red"
"lemonhd.club" = "lemonhd.club"
"njtupt.top" = "njtupt.top"
"pt.btschool.club" = "pt.btschool.club"
"www.qingwapt.com" = "www.qingwapt.com"
"hdfans.org" = "hdfans.org"
"hdarea.club" = "hdarea.club"
"pterclub.net" = "pterclub.net"
"kufei.org" = "kufei.org"
"pt.hdclone.org" = "pt.hdclone.org"
"rousi.zip" = "rousi.zip"
"www.icc2022.com" = "www.icc2022.com"
"1ptba.com" = "1ptba.com"
"ptsbao.club" = "ptsbao.club"
"www.devtracker.me" = "www.devtracker.me"
"cyanbug.net" = "cyanbug.net"
"pandapt.net" = "pandapt.net"
"totheglory.im" = "totheglory.im"
"www.ptzone.xyz" = "www.ptzone.xyz"
"pt.soulvoice.club" = "pt.soulvoice.club"
"pt.0ff.cc" = "pt.0ff.cc"
"hdatmos.club" = "hdatmos.club"
"hdhome.org" = "hdhome.org"
"hdtime.org" = "hdtime.org"
"pt.upxin.net" = "pt.upxin.net"
"www.joyhd.net" = "www.joyhd.net"
"www.okpt.net" = "www.okpt.net"
"www.oshen.win" = "www.oshen.win"
"ptchina.org" = "ptchina.org"
"pthome.net" = "pthome.net"
"ptcafe.club" = "ptcafe.club"
"crabpt.vip" = "crabpt.vip"
"www.dragonhd.xyz" = "www.dragonhd.xyz"
"hspt.club" = "hspt.club"
"hdbao.cc" = "hdbao.cc"
"www.ptlover.cc" = "www.ptlover.cc"
"ptfans.cc" = "ptfans.cc"
"pt.gtkpw.xyz" = "pt.gtkpw.xyz"
"hdpt.xyz" = "hdpt.xyz"
"www.hitpt.com" = "www.hitpt.com"
"sanpro.pw" = "sanpro.pw"
"torrenthub.club" = "torrenthub.club"
"pt.xingyungept.org" = "pt.xingyungept.org"
"cspt.top" = "cspt.top"
"tmpt.top" = "tmpt.top"
"hudbt.hust.edu.cn" = "hudbt.hust.edu.cn"
"nanyangpt.com" = "nanyangpt.com"
"tjupt.org" = "tjupt.org"
"wintersakura.net" = "wintersakura.net"
"et8.org" = "et8.org"
"pt.eastgame.org" = "pt.eastgame.org"
"hdvideo.one" = "hdvideo.one"
"hdcity.city" = "hdcity.city"
"www.hddolby.com" = "www.hddolby.com"
"52pt.site" = "52pt.site"
"audiences.me" = "audiences.me"
"pt.ying.us.kg" = "pt.ying.us.kg"
"sewerpt.com" = "sewerpt.com"
"lemonhd.net" = "lemonhd.net"
"bilibili.download" = "bilibili.download"
"pt.novahd.top" = "pt.novahd.top"
"duckboobee.org" = "duckboobee.org"
"pt.luckpt.de" = "pt.luckpt.de"
"pt.lajidui.top" = "pt.lajidui.top"
"13city.org" = "13city.org"
"zrpt.cc" = "zrpt.cc"
"www.yhpp.cc" = "www.yhpp.cc"
"pt.muxuege.org" = "pt.muxuege.org"
"cc.mypt.cc" = "cc.mypt.cc"
"nex.jivon.de" = "nex.jivon.de"
"sbpt.link" = "sbpt.link"
"pt.aling.de" = "pt.aling.de"
"cangbao.ge" = "cangbao.ge"
"dubhe.site" = "dubhe.site"
"ptlao.top" = "ptlao.top"
"longpt.org" = "longpt.org"

[userid]                                            #目标站的uid用引号包围，一般在个人详情页面中能够查看到，不配置则不会向该站发布
"www.agsvpt.com" = ""
"ptvicomo.net" = ""
"ubits.club" = ""
"www.hdkyl.in" = ""
"carpt.net" = ""
"ptlgs.org" = ""
"zmpt.cc" = ""
"raingfh.top" = ""
"leaves.red" = ""
"lemonhd.club" = ""
"njtupt.top" = ""
"pt.btschool.club" = ""
"www.qingwapt.com" = ""
"hdfans.org" = ""
"hdarea.club" = ""
"pterclub.net" = ""
"kufei.org" = ""
"pt.hdclone.org" = ""
"rousi.zip" = ""
"www.icc2022.com" = ""
"1ptba.com" = ""
"ptsbao.club" = ""
"www.devtracker.me" = ""
"cyanbug.net" = ""
"pandapt.net" = ""
"totheglory.im" = ""
"www.ptzone.xyz" = ""
"pt.soulvoice.club" = ""
"pt.0ff.cc" = ""
"hdatmos.club" = ""
"hdhome.org" = ""
"hdtime.org" = ""
"pt.upxin.net" = ""
"www.joyhd.net" = ""
"www.okpt.net" = ""
"www.oshen.win" = ""
"ptchina.org" = ""
"pthome.net" = ""
"ptcafe.club" = ""
"crabpt.vip" = ""
"www.dragonhd.xyz" = ""
"hspt.club" = ""
"hdbao.cc" = ""
"www.ptlover.cc" = ""
"ptfans.cc" = ""
"pt.gtkpw.xyz" = ""
"hdpt.xyz" = ""
"www.hitpt.com" = ""
"sanpro.pw" = ""
"torrenthub.club" = ""
"pt.xingyungept.org" = ""
"cspt.top" = ""
"tmpt.top" = ""
"hudbt.hust.edu.cn" = ""
"nanyangpt.com" = ""
"tjupt.org" = ""
"wintersakura.net" = ""
"et8.org" = ""
"pt.eastgame.org" = ""
"hdvideo.one" = ""
"hdcity.city" = ""
"www.hddolby.com" = ""
"52pt.site" = ""
"audiences.me" = ""
"pt.ying.us.kg" = ""
"sewerpt.com" = ""
"lemonhd.net" = ""
"bilibili.download" = ""
"pt.novahd.top" = ""
"duckboobee.org" = ""
"pt.luckpt.de" = ""
"pt.lajidui.top" = ""
"13city.org" = ""
"zrpt.cc" = ""
"www.yhpp.cc" = ""
"pt.muxuege.org" = ""
"cc.mypt.cc" = ""
"nex.jivon.de" = ""
"sbpt.link" = ""
"pt.aling.de" = ""
"cangbao.ge" = ""
"dubhe.site" = ""
"ptlao.top" = ""
"longpt.org" = ""

[cookies]                                           #源站和目标站的cookies信息，可在浏览器命令行输入document.cookie打印后直接复制放入。
"www.agsvpt.com" = ""
"ptvicomo.net" = ""
"ubits.club" = ""
"www.hdkyl.in" = ""
"carpt.net" = ""
"ptlgs.org" = ""
"zmpt.cc" = ""
"raingfh.top" = ""
"leaves.red" = ""
"lemonhd.club" = ""
"njtupt.top" = ""
"pt.btschool.club" = ""
"www.qingwapt.com" = ""
"hdfans.org" = ""
"hdarea.club" = ""
"pterclub.net" = ""
"kufei.org" = ""
"pt.hdclone.org" = ""
"rousi.zip" = ""
"www.icc2022.com" = ""
"1ptba.com" = ""
"ptsbao.club" = ""
"www.devtracker.me" = ""
"cyanbug.net" = ""
"pandapt.net" = ""
"totheglory.im" = ""
"www.ptzone.xyz" = ""
"pt.soulvoice.club" = ""
"pt.0ff.cc" = ""
"hdatmos.club" = ""
"hdhome.org" = ""
"hdtime.org" = ""
"pt.upxin.net" = ""
"www.joyhd.net" = ""
"www.okpt.net" = ""
"www.oshen.win" = ""
"ptchina.org" = ""
"pthome.net" = ""
"ptcafe.club" = ""
"crabpt.vip" = ""
"www.dragonhd.xyz" = ""
"hspt.club" = ""
"hdbao.cc" = ""
"www.ptlover.cc" = ""
"ptfans.cc" = ""
"pt.gtkpw.xyz" = ""
"hdpt.xyz" = ""
"www.hitpt.com" = ""
"sanpro.pw" = ""
"torrenthub.club" = ""
"pt.xingyungept.org" = ""
"cspt.top" = ""
"tmpt.top" = ""
"hudbt.hust.edu.cn" = ""
"nanyangpt.com" = ""
"tjupt.org" = ""
"wintersakura.net" = ""
"et8.org" = ""
"pt.eastgame.org" = ""
"hdvideo.one" = ""
"hdcity.city" = ""
"www.hddolby.com" = ""
"52pt.site" = ""
"audiences.me" = ""
"pt.ying.us.kg" = ""
"sewerpt.com" = ""
"lemonhd.net" = ""
"bilibili.download" = ""
"pt.novahd.top" = ""
"duckboobee.org" = ""
"pt.luckpt.de" = ""
"pt.lajidui.top" = ""
"13city.org" = ""
"zrpt.cc" = ""
"www.yhpp.cc" = ""
"pt.muxuege.org" = ""
"cc.mypt.cc" = ""
"nex.jivon.de" = ""
"sbpt.link" = ""
"pt.aling.de" = ""
"cangbao.ge" = ""
"dubhe.site" = ""
"ptlao.top" = ""
"longpt.org" = ""

[priority]                                           #设置目标站的优先级，数字越小优先级越高，如0-999，0最优先。
"www.agsvpt.com" = 999
"ptvicomo.net" = 999
"ubits.club" = 999
"www.hdkyl.in" = 999
"carpt.net" = 999
"ptlgs.org" = 999
"zmpt.cc" = 999
"raingfh.top" = 999
"leaves.red" = 999
"lemonhd.club" = 999
"njtupt.top" = 999
"pt.btschool.club" = 999
"www.qingwapt.com" = 999
"hdfans.org" = 999
"hdarea.club" = 999
"pterclub.net" = 999
"kufei.org" = 999
"pt.hdclone.org" = 999
"rousi.zip" = 999
"www.icc2022.com" = 999
"1ptba.com" = 999
"ptsbao.club" = 999
"www.devtracker.me" = 999
"cyanbug.net" = 999
"pandapt.net" = 999
"totheglory.im" = 999
"www.ptzone.xyz" = 999
"pt.soulvoice.club" = 999
"pt.0ff.cc" = 999
"hdatmos.club" = 999
"hdhome.org" = 999
"hdtime.org" = 999
"pt.upxin.net" = 999
"www.joyhd.net" = 999
"www.okpt.net" = 999
"www.oshen.win" = 999
"ptchina.org" = 999
"pthome.net" = 999
"ptcafe.club" = 999
"crabpt.vip" = 999
"www.dragonhd.xyz" = 999
"hspt.club" = 999
"hdbao.cc" = 999
"www.ptlover.cc" = 999
"ptfans.cc" = 999
"pt.gtkpw.xyz" = 999
"hdpt.xyz" = 999
"www.hitpt.com" = 999
"sanpro.pw" = 999
"torrenthub.club" = 999
"pt.xingyungept.org" = 999
"cspt.top" = 999
"tmpt.top" = 999
"hudbt.hust.edu.cn" = 999
"nanyangpt.com" = 999
"tjupt.org" = 999
"wintersakura.net" = 999
"et8.org" = 999
"pt.eastgame.org" = 999
"hdvideo.one" = 999
"hdcity.city" = 999
"www.hddolby.com" = 999
"52pt.site" = 999
"audiences.me" = 999
"pt.ying.us.kg" = 999
"sewerpt.com" = 999
"lemonhd.net" = 999
"bilibili.download" = 999
"pt.novahd.top" = 999
"duckboobee.org" = 999
"pt.luckpt.de" = 999
"pt.lajidui.top" = 999
"13city.org" = 999
"zrpt.cc" = 999
"www.yhpp.cc" = 999
"pt.muxuege.org" = 999
"cc.mypt.cc" = 999
"nex.jivon.de" = 999
"sbpt.link" = 999
"pt.aling.de" = 999
"cangbao.ge" = 999
"dubhe.site" = 999
"ptlao.top" = 999
"longpt.org" = 999

[image_bed]
bed_use = ""                                        #图床使用开关，agsvpt|smms|ptdream|pixhost，N选一填入
picture_type = "PNG"                                #使用截图的后缀，JPG|PNG，二选一填入。如果选PNG，会无视源站截图重新截取。如果选JPG，优先用源站，若无则截取为九宫格。
pieces = 4                                          #截取N张图片

[image_bed.token]                                   #图床的认证token，建议对免费公共图床建多个账号获取token，防止上传超限。
agsvpt = ["", "", ""]                               #如果只有一个token：agsv=['1']
smms = ["", "", ""]                                 #如果有多个token：agsv=['1','2']，agsv=['1','2','3','4']
ptdream = ["", "", ""]                              #每个图床都可以如此设置
pixhost = [""]                                      #pixhost图床留空即可

[image_bed.image_bed_email]                         #图床登录账号
agsvpt = ""

[image_bed.image_bed_pw]                            #图床登录密码
agsvpt = ""

[qiyeweixin]                                        #配置企业微信推送信息相关内容
is_used = false                                     #是否启用企业微信通知功能。默认关闭
corpsecret = ""                                     #打开https://work.weixin.qq.com/wework_admin/frame页面，从应用管理标签中的自定义应用详情页面中Secret内容
agentid = ""                                        #打开https://work.weixin.qq.com/wework_admin/frame页面，从应用管理标签中的自定义应用详情页面中AgentId内容
corpid = ""                                         #打开https://work.weixin.qq.com/wework_admin/frame页面，从我的企业标签中的企业ID
userid = ""                                         #打开https://work.weixin.qq.com/wework_admin/frame页面，从通讯录标签中成员详情中的账号
mobile = ""                                         #打开https://work.weixin.qq.com/wework_admin/frame页面，从通讯录标签中成员详情中的手机
ACCESS_TOKEN = ""                                   #留空，代码会自动生成

[email]                                             #配置邮件推送信息相关内容
is_used = false                                     #是否启用邮件通知功能。默认关闭
SMTP_SERVER = ""                                    #SMTP发送邮件服务器，形如 smtp.exmail.qq.com:465
SMTP_SSL = false                                    #SMTP发送邮件服务器是否使用 SSL，填写 true 或 false
SMTP_EMAIL = ""                                     #SMTP收发件邮箱，通知将会由自己发给自己
SMTP_PASSWORD = ""                                  #SMTP登录密码，也可能为特殊口令，视具体邮件服务商说明而定
SMTP_NAME = ""                                      #SMTP收发件人姓名，可随意填写

[iyuu]                                              #配置IYUU推送信息相关内容
is_used = false                                     #是否启用IYUU通知功能。默认关闭
iyuu_token = ""                                     #IYUU的token